In [141]:
#  import Libirary
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [142]:
df  = pd.read_csv('/content/House_price.csv.csv')

In [143]:
df.head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [144]:
df.tail()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0

In [145]:
print("Rows and Columns:",df.shape)

Rows and Columns: (13320, 9)

In [146]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [147]:
df.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [149]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [150]:
df = df.drop(columns='availability')
df = df.drop(columns='society')

In [151]:
df.head()

,area_type,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [152]:
df.isnull().sum()

area_type       0
location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [153]:
df['bath'] = df['bath'].fillna(df['bath'].mean())
df['balcony'] = df['balcony'].fillna(df['balcony'].mean())

In [154]:
df.isnull().sum()

area_type      0
location       1
size          16
total_sqft     0
bath           0
balcony        0
price          0
dtype: int64

In [155]:
df = df.dropna()

In [156]:
df.isnull().sum()

area_type     0
location      0
size          0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [157]:
df.duplicated().sum()

np.int64(691)

In [158]:
df = df.drop_duplicates()

In [159]:
print("Rows and Column:",df.shape)

Rows and Column: (12612, 7)

In [160]:
df.head()

,area_type,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Kothanur,2 BHK,1200,2.0,1.0,51.00

In [161]:
df.dtypes

area_type      object
location       object
size           object
total_sqft     object
bath          float64
balcony       float64
price         float64
dtype: object

In [162]:
df.rename(columns={"size": "bhk"}, inplace=True)

In [163]:
df['bhk'].head()

0        2 BHK
1    4 Bedroom
2        3 BHK
3        3 BHK
4        2 BHK
Name: bhk, dtype: object

In [164]:
df.isnull().sum()

area_type     0
location      0
bhk           0
total_sqft    0
bath          0
balcony       0
price         0
dtype: int64

In [165]:
df.drop("area_type", axis=1, inplace=True)

In [166]:
df.head()

                   location        bhk total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [168]:
def convert_sqft(x):
    try:
        if isinstance(x, str):
            x = x.strip()

            # Handle range: 1200-1400
            if "-" in x:
                a, b = x.split("-")
                return (float(a) + float(b)) / 2

            # Handle square meter
            if "Sq. Meter" in x:
                value = float(x.replace("Sq. Meter", "").strip())
                return value * 10.7639

            return float(x)

        return float(x)

    except:
        return None


df["sqft"] = df["total_sqft"].apply(convert_sqft)

In [169]:
df = df.drop(columns='total_sqft')

In [175]:
df["bhk"] = df["bhk"].str.extract(r"(\d+)").astype(float)

In [182]:
df['price_per_sqft'] = df['price'] / df['sqft']*100000

In [183]:
df.head()

,location,bhk,bath,balcony,price,sqft,price_per_sqft
0,Electronic City Phase II,2.0,2.0,1.0,39.07,1056.0,3699.810606
1,Chikka Tirupathi,4.0,5.0,3.0,120.00,2600.0,4615.384615
2,Uttarahalli,3.0,2.0,3.0,62.00,1440.0,4305.555556
3,Lingadheeranahalli,3.0,3.0,1.0,95.00,1521.0,6245.890861
4,Kothanur,2.0,2.0,1.0,51.00,1200.0,4250.000000

In [186]:
df.shape

(12612, 7)

In [188]:
df.dtypes

location           object
bhk               float64
bath              float64
balcony           float64
price             float64
sqft              float64
price_per_sqft    float64
dtype: object

In [192]:
df["location"] = df["location"].str.strip()
df["location"] = df["location"].str.replace(r"\s+", " ", regex=True)

In [193]:
print(df["location"].nunique())
print(df["location"].value_counts().head(20))

1293
location
Whitefield                  514
Sarjapur Road               366
Electronic City             282
Thanisandra                 232
Kanakpura Road              230
Yelahanka                   209
Marathahalli                166
Raja Rajeshwari Nagar       159
Uttarahalli                 154
Hebbal                      150
Bannerghatta Road           149
Hennur Road                 142
7th Phase JP Nagar          133
Electronic City Phase II    121
Rajaji Nagar                107
Bellandur                    93
Haralur Road                 93
KR Puram                     91
Hoodi                        88
Electronics City Phase 1     88
Name: count, dtype: int64

In [194]:
location_counts = df["location"].value_counts()

print("Unique locations:", df["location"].nunique())
print("Locations with <10 properties:", (location_counts < 10).sum())

Unique locations: 1293
Locations with <10 properties: 1044

In [196]:
print(df.shape)
print(df.isnull().sum())
print(df.dtypes)

(12612, 7)
location           0
bhk                0
bath               0
balcony            0
price              0
sqft              29
price_per_sqft    29
dtype: int64
location           object
bhk               float64
bath              float64
balcony           float64
price             float64
sqft              float64
price_per_sqft    float64
dtype: object

In [197]:
df.head()

,location,bhk,bath,balcony,price,sqft,price_per_sqft
0,Electronic City Phase II,2.0,2.0,1.0,39.07,1056.0,3699.810606
1,Chikka Tirupathi,4.0,5.0,3.0,120.00,2600.0,4615.384615
2,Uttarahalli,3.0,2.0,3.0,62.00,1440.0,4305.555556
3,Lingadheeranahalli,3.0,3.0,1.0,95.00,1521.0,6245.890861
4,Kothanur,2.0,2.0,1.0,51.00,1200.0,4250.000000

In [200]:
df.isnull().sum()

location           0
bhk                0
bath               0
balcony            0
price              0
sqft              29
price_per_sqft    29
dtype: int64

In [221]:
df['sqft'] = df['sqft'].fillna(df['sqft'].mean())
df['price_per_sqft'] = df['price_per_sqft'].fillna(df['price_per_sqft'].mean())
df = df.drop_duplicates()

/tmp/ipykernel_1755/917906937.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sqft'] = df['sqft'].fillna(df['sqft'].mean())
/tmp/ipykernel_1755/917906937.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_per_sqft'] = df['price_per_sqft'].fillna(df['price_per_sqft'].mean())

In [222]:
df.head()

,location,bhk,bath,balcony,price,sqft,price_per_sqft
0,Electronic City Phase II,2.0,2.0,1.0,39.07,1056.0,3699.810606
1,Chikka Tirupathi,4.0,5.0,3.0,120.00,2600.0,4615.384615
2,Uttarahalli,3.0,2.0,3.0,62.00,1440.0,4305.555556
3,Lingadheeranahalli,3.0,3.0,1.0,95.00,1521.0,6245.890861
4,Kothanur,2.0,2.0,1.0,51.00,1200.0,4250.000000

In [224]:
df.to_csv("cleaned_house_price.csv", index=False)

In [225]:
from google.colab import files
files.download("cleaned_house_price.csv")